#!/bin/sh
set -e

# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p clamprotect /usr/share/clamprotect
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p clamprotect /usr/share/clamprotect || true
fi

# End automatically added section
